# Generated by Django 4.1.7 on 2023-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('description', models.TextField()),
                ('reviews', models.TextField()),
                ('services', models.TextField()),
                ('coordinates', models.TextField()),
                ('price', models.FloatField()),
                ('stars', models.IntegerField()),
                ('hotelImg', models.ImageField(upload_to='hotels')),
            ],
            options={
                'verbose_name': 'Hotels',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
