# Generated by Django 4.1.7 on 2023-05-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='placementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfInstitution', models.CharField(max_length=100, verbose_name='Тип заведения')),
            ],
            options={
                'verbose_name': 'Placment type',
                'verbose_name_plural': 'Placment type',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
