# Generated by Django 4.1.7 on 2023-05-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_placementtype_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='stars',
        ),
    ]
