# Generated by Django 4.1.7 on 2023-05-02 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_hotels_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementtype',
            name='id',
        ),
        migrations.AddField(
            model_name='placementtype',
            name='hotels',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.hotels'),
            preserve_default=False,
        ),
    ]
