# Generated by Django 4.1.7 on 2023-05-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_placementtype_hotels_hotels_placementtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='services',
        ),
        migrations.AddField(
            model_name='hotels',
            name='link',
            field=models.TextField(default='14414', verbose_name='Ссылки на сайт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotels',
            name='coordinates',
            field=models.TextField(verbose_name='Координаты учреждения для яндекс карт'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='price',
            field=models.FloatField(verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
