# Generated by Django 4.1.7 on 2023-05-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_hotels_reviews_remove_hotels_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='hotelImg',
        ),
        migrations.CreateModel(
            name='HotelsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование изображения')),
                ('image', models.ImageField(upload_to='hotels_gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.hotels')),
            ],
            options={
                'verbose_name': 'Фото из гостиниц',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
