# Generated by Django 4.1.7 on 2023-05-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_hotels_hotelimg_hotelsgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelsgallery',
            options={'verbose_name': 'Фото из гостиниц', 'verbose_name_plural': 'Hotels Photo'},
        ),
        migrations.RemoveField(
            model_name='hotelsgallery',
            name='product',
        ),
        migrations.AddField(
            model_name='hotelsgallery',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='main.hotels'),
            preserve_default=False,
        ),
    ]
