# Generated by Django 4.1.7 on 2023-05-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_hotelsgallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCoordinaties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointX', models.FloatField(default=55.751574, help_text='Координата X для отображения предприятия на карте', verbose_name='X координата')),
                ('pointY', models.FloatField(default=37.573856, help_text='Координата Y для отображения предприятия на карте', verbose_name='Y координата')),
            ],
            options={
                'verbose_name': 'Координаты предприятия',
                'verbose_name_plural': 'Координаты предприятия',
            },
        ),
        migrations.CreateModel(
            name='FoodBusiness',
            fields=[
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.TextField(max_length=250, verbose_name='Адрес')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('link', models.TextField(verbose_name='Ссылки на сайт')),
                ('workingHours', models.TextField(verbose_name='Время работы')),
                ('price', models.IntegerField(verbose_name='Средний чек')),
                ('orgFoodCoord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.organizationcoordinaties')),
            ],
        ),
    ]
