# Generated by Django 4.1.7 on 2023-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_organizationcoordinaties_foodbusiness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodbusiness',
            options={'verbose_name': 'Общепит', 'verbose_name_plural': 'Общепит'},
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=20000, verbose_name='Описание'),
        ),
    ]
