# Generated by Django 4.1.7 on 2023-05-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_foodbusiness_options_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbusiness',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodbusiness',
            name='orgFoodCoord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizationcoordinaties'),
        ),
    ]
