# Generated by Django 4.1.7 on 2023-05-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_organizationcoordinaties_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfKitchen', models.CharField(max_length=100, verbose_name='Тип кухни')),
            ],
            options={
                'verbose_name': 'Тип кухни',
                'verbose_name_plural': 'Тип кухни',
            },
        ),
        migrations.AlterField(
            model_name='foodbusiness',
            name='orgFoodCoord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organizationcoordinaties'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='placementType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.placementtype'),
        ),
        migrations.AlterField(
            model_name='hotelsgallery',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_images', to='main.hotels'),
        ),
        migrations.AddField(
            model_name='foodbusiness',
            name='kitchenType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kitchentype'),
        ),
    ]
