# Generated by Django 4.1.7 on 2023-05-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_lookstype_foodbusinessgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'verbose_name': 'Отели', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='placementtype',
            options={'verbose_name': 'Тип заведения', 'verbose_name_plural': 'Тип заведения'},
        ),
        migrations.RenameField(
            model_name='foodbusinessgallery',
            old_name='hotel',
            new_name='foodBusiness',
        ),
        migrations.AddField(
            model_name='hotels',
            name='workingHours',
            field=models.TextField(default=1, verbose_name='Время работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotels',
            name='address',
            field=models.TextField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organizationcoordinaties'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=models.TextField(max_length=40000, verbose_name='Описание'),
        ),
    ]
