# Generated by Django 4.1.7 on 2023-05-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_hotels_options_alter_placementtype_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LooksType',
            new_name='ShowplacesType',
        ),
        migrations.RenameField(
            model_name='placementtype',
            old_name='typeOfInstitution',
            new_name='typeOfPlacment',
        ),
    ]
