# Generated by Django 4.1.7 on 2023-05-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_lookstype_showplacestype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationcoordinaties',
            options={'verbose_name': 'Координаты предприятий', 'verbose_name_plural': 'Координаты предприятия'},
        ),
    ]
