# Generated by Django 4.1.7 on 2023-05-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_showplaces_alter_organizationcoordinaties_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showplaces',
            options={'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательности'},
        ),
    ]
