# Generated by Django 4.1.7 on 2023-05-09 12:20

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_showplaces_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
