# Generated by Django 4.1.7 on 2023-05-09 14:24

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_news_content_alter_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiteInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationTitle', froala_editor.fields.FroalaField()),
                ('organizationContacts', froala_editor.fields.FroalaField()),
                ('organizationDeveloper', froala_editor.fields.FroalaField()),
                ('organizationVideo', models.FileField(upload_to='indexPageVideo')),
                ('organizationVideoContentHeader', models.CharField(max_length=30, verbose_name='заголовок видео')),
                ('organizationVideoContentDescription', models.CharField(max_length=30, verbose_name='описание видео')),
            ],
            options={
                'verbose_name': 'OrganizationDB',
                'verbose_name_plural': 'OrganizationDB',
            },
        ),
        migrations.CreateModel(
            name='OrganizationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование изображения')),
                ('image', models.ImageField(upload_to='OrganizationDB_gallery/%Y/%m/%d/')),
                ('contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Showplaces_images', to='main.citeinformations')),
            ],
            options={
                'verbose_name': 'Фото для слайдера',
                'verbose_name_plural': 'Фото для слайдера',
            },
        ),
    ]
