# Generated by Django 4.1.7 on 2023-05-13 12:01

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_citeinformations_organizationgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
