# Generated by Django 4.1.7 on 2023-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_hotels_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfFood', models.CharField(max_length=100, verbose_name='Вид еды')),
            ],
            options={
                'verbose_name': 'Вид еды',
                'verbose_name_plural': 'Вид еды',
            },
        ),
    ]
