# Generated by Django 4.1.7 on 2023-05-13 18:28

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbusiness',
            name='foodType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.foodtype'),
        ),
        migrations.AlterField(
            model_name='foodbusiness',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='showplaces',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
