# Generated by Django 4.1.7 on 2023-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_foodbusiness_foodtype_alter_foodbusiness_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='isShowedInIndexPage',
            field=models.BooleanField(default=True, verbose_name='Показывать карточку организации на главной странице'),
            preserve_default=False,
        ),
    ]
