# Generated by Django 4.1.7 on 2023-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_hotels_isshowedinindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbusiness',
            name='isShowedInIndexPage',
            field=models.BooleanField(default=True, verbose_name='Показывать карточку организации на главной странице'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showplaces',
            name='isShowedInIndexPage',
            field=models.BooleanField(default=False, verbose_name='Показывать карточку организации на главной странице'),
            preserve_default=False,
        ),
    ]
