# Generated by Django 4.1.7 on 2023-05-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_foodbusiness_isshowedinindexpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitchentype',
            options={'verbose_name': 'Формат общепита', 'verbose_name_plural': 'Формат общепита'},
        ),
    ]
