# Generated by Django 4.1.7 on 2023-05-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_kitchentype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementtype',
            options={'verbose_name': 'Формат отеля', 'verbose_name_plural': 'Формат отеля'},
        ),
        migrations.AlterModelOptions(
            name='showplacestype',
            options={'verbose_name': 'Формат достопримечательности', 'verbose_name_plural': 'Формат достопримечательности'},
        ),
    ]
