# Generated by Django 4.1.7 on 2023-05-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_placementtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organizationcoordinaties', verbose_name='Координаты'),
        ),
    ]
