# Generated by Django 4.1.7 on 2023-05-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_hotels_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='placementType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.placementtype', verbose_name='Заведение'),
        ),
    ]
