# Generated by Django 4.1.7 on 2023-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_citeinformations_organizationvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citeinformations',
            name='organizationDeveloperImage',
            field=models.ImageField(default='', upload_to='developer_img/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
