# Generated by Django 4.1.7 on 2023-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_excursion_excursiontype_routecoordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='routeCoordinaties',
            field=models.ManyToManyField(null=True, related_name='ex_route', to='main.organizationcoordinaties', verbose_name='экскурсия'),
        ),
        migrations.DeleteModel(
            name='RouteCoordinates',
        ),
    ]
