# Generated by Django 4.1.7 on 2023-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_excursion_routecoordinaties_delete_routecoordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiteTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название тега')),
            ],
        ),
        migrations.AddField(
            model_name='foodbusiness',
            name='tags',
            field=models.ManyToManyField(null=True, to='main.citetags', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='tags',
            field=models.ManyToManyField(null=True, to='main.citetags', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='showplaces',
            name='tags',
            field=models.ManyToManyField(null=True, to='main.citetags', verbose_name='Тэги'),
        ),
    ]
