# Generated by Django 4.1.7 on 2023-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_citetags_options_excursion_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='exDuration',
            field=models.IntegerField(max_length=20, verbose_name='Продолжительность экскурсии'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='hotel_tags', to='main.citetags', verbose_name='Тэги'),
        ),
    ]
